### PR TITLE
Implements `__hash__` for collections

### PR DESCRIPTION
**Pull request by FlickerSoul**
This PR adds `__hash__` to `HashTrieSet`, `HashTrieMap`, and `List` so that the instances of them are hashable (if underlaying elements are hashable). 

Related to #50

### CODE REVIEW

**Comment by FlickerSoul** [comment]
@Julian Hi Julian, just a friendly ping, this PR is ready for review whenever you're ready :))

**Comment by Julian** [comment]
Hey! Apologies, I missed it! Thanks for the ping, will have a look.

**Comment by Julian** [comment]
I've been a bit tied up but just mentioning I still will try to look at this in the next few days, sorry for the delay!

**Comment by FlickerSoul** [comment]
No worries at all! Take your time :))

**Comment by Julian** [comment]
Thanks again, good work! I've merged and tagged a release, so this should go out imminently.

**Pull request merged**
