### PR TITLE
Fix hashing overflow issues (#86)

### PR DESCRIPTION
**Pull request by FlickerSoul**
This PR fixes overflow errors during hashing persistent data structures.

### CODE REVIEW

**Comment by Julian** [comment]
Nice! Any chance you also might take a stab at the suggestion to run with `--profile=dev` in CI? I'm not 100% sure what it does (so a good first step is probably double checking) but if we don't add it, it's obviously likely we could accidentally add some other thing which trips it.

**Comment by FlickerSoul** [comment]
It looks like the arguments are passed to `maturin` and then to `cargo` during building `rpds`. See [here](https://doc.rust-lang.org/cargo/reference/profiles.html#dev) and [here](https://www.maturin.rs/local_development). The dev profile enables the overflow check and that's why we see the errors in the issue.

**Comment by Julian** [comment]
From that page it would seem like we should run with `--profile=test`, which implies dev.

**Comment by FlickerSoul** [comment]
Yes I think `test` would make more sense. I can modify the CI to do that :)

**Comment by Julian** [comment]
@FlickerSoul let me know if you're still up for making the CI change! (Thanks again for your work so far)

**Pull request merged**
